package com.lcl.greendao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lcl.greendao.bean.DanmakuInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "danmaku".
*/
public class DanmakuInfoDao extends AbstractDao<DanmakuInfo, Long> {

    public static final String TABLENAME = "danmaku";

    /**
     * Properties of entity DanmakuInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Type = new Property(1, int.class, "type", false, "TYPE");
        public final static Property Content = new Property(2, String.class, "content", false, "CONTENT");
        public final static Property Time = new Property(3, long.class, "time", false, "TIME");
        public final static Property TextSize = new Property(4, float.class, "textSize", false, "TEXT_SIZE");
        public final static Property TextColor = new Property(5, int.class, "textColor", false, "TEXT_COLOR");
        public final static Property UserName = new Property(6, String.class, "userName", false, "USER_NAME");
        public final static Property Vid = new Property(7, String.class, "vid", false, "VID");
    }


    public DanmakuInfoDao(DaoConfig config) {
        super(config);
    }
    
    public DanmakuInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"danmaku\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TYPE\" INTEGER NOT NULL ," + // 1: type
                "\"CONTENT\" TEXT," + // 2: content
                "\"TIME\" INTEGER NOT NULL ," + // 3: time
                "\"TEXT_SIZE\" REAL NOT NULL ," + // 4: textSize
                "\"TEXT_COLOR\" INTEGER NOT NULL ," + // 5: textColor
                "\"USER_NAME\" TEXT," + // 6: userName
                "\"VID\" TEXT);"); // 7: vid
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"danmaku\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DanmakuInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getType());
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(3, content);
        }
        stmt.bindLong(4, entity.getTime());
        stmt.bindDouble(5, entity.getTextSize());
        stmt.bindLong(6, entity.getTextColor());
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(7, userName);
        }
 
        String vid = entity.getVid();
        if (vid != null) {
            stmt.bindString(8, vid);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DanmakuInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getType());
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(3, content);
        }
        stmt.bindLong(4, entity.getTime());
        stmt.bindDouble(5, entity.getTextSize());
        stmt.bindLong(6, entity.getTextColor());
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(7, userName);
        }
 
        String vid = entity.getVid();
        if (vid != null) {
            stmt.bindString(8, vid);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DanmakuInfo readEntity(Cursor cursor, int offset) {
        DanmakuInfo entity = new DanmakuInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // type
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // content
            cursor.getLong(offset + 3), // time
            cursor.getFloat(offset + 4), // textSize
            cursor.getInt(offset + 5), // textColor
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // userName
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // vid
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DanmakuInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setType(cursor.getInt(offset + 1));
        entity.setContent(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTime(cursor.getLong(offset + 3));
        entity.setTextSize(cursor.getFloat(offset + 4));
        entity.setTextColor(cursor.getInt(offset + 5));
        entity.setUserName(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setVid(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DanmakuInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DanmakuInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DanmakuInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
