package com.lcl.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lcl.greendao.bean.DanmakuInfo;

import com.lcl.greendao.dao.DanmakuInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig danmakuInfoDaoConfig;

    private final DanmakuInfoDao danmakuInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        danmakuInfoDaoConfig = daoConfigMap.get(DanmakuInfoDao.class).clone();
        danmakuInfoDaoConfig.initIdentityScope(type);

        danmakuInfoDao = new DanmakuInfoDao(danmakuInfoDaoConfig, this);

        registerDao(DanmakuInfo.class, danmakuInfoDao);
    }
    
    public void clear() {
        danmakuInfoDaoConfig.clearIdentityScope();
    }

    public DanmakuInfoDao getDanmakuInfoDao() {
        return danmakuInfoDao;
    }

}
